baseurl = "https://crass-sandwich.com/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "docs"
author = "Chris Janidlo"
title = "crass sandwich"
disqusshortname = ""
pluralizelisttitles = false
googleAnalytics = "UA-106354054-1"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Chris Janidlo Makes Video Games. OOP design is my passion"
copyright = "Copyright © 2019 Chris Janidlo"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
itch = "crass-sandwich"
github = "crassSandwich"
email = "christopherjanidlo@gmail.com"
# linkedin = "john-example-aa80ue8è"
twitter = "crass_sandwich"
# facebook = "facebook_id"
soundcloud = "crass_sandwich"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false
highlightjslanguages = ["cs", "bash", "python"]

[params.colors]
identifier		= "#ee8a38"
identifier_dark = "#eb6e0f"
background		= "#e9e9e9"
background_dark	= "#282a36"
